@startuml

class Notification{
    - String title, message, icon, sound, priority
    - String actionButtons
    + void Show()
}

abstract class Builder{
    - String title, message, icon, sound, priority
    - String actionButtons
    + {abstract} Builder buildTitle(String title)
    + {abstract} Builder buildMessage(String message)
    + {abstract} Builder buildIcon(String icon)
    + {abstract} Builder buildSound(String sound)
    + {abstract} Builder buildPriority(String priority)
    + {abstract} Builder buildButtons(String buttons)
    + {abstract} Notification getResult()
}

class ConcreteBuilder{
    + Builder buildTitle(String title)
    + Builder buildMessage(String message)
    + Builder buildIcon(String icon)
    + Builder buildSound(String sound)
    + Builder buildPriority(String priority)
    + Builder buildButtons(String buttons)
    + Notification getResult()
}

Builder <|-- ConcreteBuilder
ConcreteBuilder ..> Notification : create

@enduml