@startuml
'https://plantuml.com/class-diagram

abstract class Nut{
    int giaTri
    +{abstract} void duyet()
    +{abstract} void themTrai(nut n)
    +{abstract} void themPhai(nut n)
    +{abstract} void xoaTrai()
    +{abstract} void xoaPhai()
}
class Nutla
class NutTrong

Nut <|-- Nutla
Nut <|-- NutTrong

NutTrong --> Nut: trai
NutTrong --> Nut: phai

@enduml